baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Europe-usa.com - Insights & Stories From the World of Online Gambling"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "Europe-usa.com is a comprehensive resource for all types of gambling, with a focus on online gambling. It is managed by a committed group of individuals with extensive gambling expertise and experience."
[params.banner]
heading = "Insights & Stories From the World of Online Gambling"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Our blog provides information on the gambling industry. We share expert advice, how-to guides, research, lists, reviews, interviews, and much more!"
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Looking for more information about something you've seen on our site? Let us help you!"
enable = true
title = "Contact us for more information."
[params.footer]
address = "723 Main Street <br> New York, NY 10001"
content = "Europe-usa.com is a comprehensive resource for all types of gambling, with a focus on online gambling. It is managed by a committed group of individuals with extensive gambling expertise and experience."
copyright = "Copyright &copy; 2021 Europe-usa.com"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "About Europe-usa"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
